version=5.3.0.RELEASE
springBootVersion=2.3.9.RELEASE
org.gradle.jvmargs=-Xmx1536m
repoGroupUrl=http://10.0.1.232:8081/repository/public/
repoReleaseUrl=http://10.0.1.232:8081/repository/releases/
repoSnapshotUrl=http://10.0.1.232:8081/repository/snapshots/
repoThirdpartyUrl=http://10.0.1.232:8081/repository/third-party/
nexusUsername=developer
nexusPassword=noaats00!

